-- Core MyResCal schema.
-- Idempotent: safe to run more than once.

create extension if not exists pgcrypto;

create table if not exists public.properties (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null,
  name text not null,
  description text,
  created_at timestamp with time zone default now()
);

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null,
  property_id uuid not null references public.properties(id) on delete cascade,
  name text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  owner_id uuid,
  property_id uuid,
  room_id uuid,
  name text not null,
  lastname text not null,
  phone text,
  mail text,
  start_date date not null,
  end_date date not null,
  adults integer default 0,
  children integer default 0,
  status text default 'preliminary',
  notes text,
  nightly_rate numeric,
  total_price numeric,
  deposit_amount numeric,
  confirmation_method text,
  created_at timestamp with time zone default now()
);

alter table public.properties
  add column if not exists owner_id uuid,
  add column if not exists name text,
  add column if not exists description text,
  add column if not exists created_at timestamp with time zone default now();

alter table public.rooms
  add column if not exists owner_id uuid,
  add column if not exists property_id uuid,
  add column if not exists name text,
  add column if not exists created_at timestamp with time zone default now();

alter table public.reservations
  add column if not exists owner_id uuid,
  add column if not exists property_id uuid,
  add column if not exists room_id uuid,
  add column if not exists status text default 'preliminary',
  add column if not exists notes text,
  add column if not exists nightly_rate numeric,
  add column if not exists total_price numeric,
  add column if not exists deposit_amount numeric,
  add column if not exists confirmation_method text;

update public.reservations
set status = case
  when status is null or btrim(status) = '' then 'preliminary'
  when lower(btrim(status)) in ('booking', 'confirmed') then 'confirmed'
  else btrim(status)
end
where status is null
  or btrim(status) = ''
  or status <> btrim(status)
  or lower(btrim(status)) in ('booking', 'confirmed');

update public.reservations
set confirmation_method = case
  when status = 'confirmed'
    and confirmation_method in ('paid_full', 'booking_com', 'other')
    then confirmation_method
  when status = 'confirmed' then 'booking_com'
  else null
end
where status = 'confirmed'
  or confirmation_method is not null;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'reservations'
      and column_name = 'price'
  ) then
    execute '
      update public.reservations
      set total_price = price
      where total_price is null and price is not null
    ';
  end if;
end $$;

do $$
begin
  alter table public.rooms
    add constraint rooms_property_fk foreign key (property_id)
    references public.properties(id) on delete cascade;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.reservations
    add constraint reservations_property_fk foreign key (property_id)
    references public.properties(id) on delete set null;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.reservations
    add constraint reservations_room_fk foreign key (room_id)
    references public.rooms(id) on delete set null;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.reservations
    add constraint reservations_status_check
    check (status in ('preliminary', 'deposit_paid', 'confirmed', 'past'));
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.reservations
    add constraint reservations_confirmation_method_check
    check (
      (
        status = 'confirmed'
        and confirmation_method in ('paid_full', 'booking_com', 'other')
      )
      or (
        status <> 'confirmed'
        and confirmation_method is null
      )
    );
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.reservations
    add constraint reservations_nightly_rate_non_negative
    check (nightly_rate is null or nightly_rate >= 0);
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.reservations
    add constraint reservations_total_price_non_negative
    check (total_price is null or total_price >= 0);
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.reservations
    add constraint reservations_deposit_amount_non_negative
    check (deposit_amount is null or deposit_amount >= 0);
exception
  when duplicate_object then null;
end $$;

create index if not exists properties_owner_idx on public.properties(owner_id);
create index if not exists rooms_owner_idx on public.rooms(owner_id);
create index if not exists rooms_property_idx on public.rooms(property_id);
create unique index if not exists rooms_property_name_unique
  on public.rooms(owner_id, property_id, lower(btrim(name)));
create index if not exists reservations_owner_idx on public.reservations(owner_id);
create index if not exists reservations_property_idx on public.reservations(property_id);
create index if not exists reservations_room_idx on public.reservations(room_id);
create index if not exists reservations_room_dates_idx
  on public.reservations(room_id, start_date, end_date);
